version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-cert.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
    restart: always

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot 
      --email maitreyavaidyam@gmail.com 
      --agree-tos --no-eff-email -v
      -d ctdoj.credenz.co.in"
