server {
    listen 80;
    server_name ctdoj.credenz.co.in;
    return 301 https://$host$request_uri;  # redirect all HTTP to HTTPS
}

server {
    listen 443 ssl;
    server_name ctdoj.credenz.co.in;

    ssl_certificate /etc/letsencrypt/live/ctdoj.credenz.co.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ctdoj.credenz.co.in/privkey.pem;

    # SSE: /submission/sse/<submission_id>
    location ~ ^/submission/sse/ {
        proxy_pass http://node-backend:3000;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_cache off;
        gzip off;
        chunked_transfer_encoding off;
        proxy_read_timeout 1h;
        proxy_send_timeout 1h;
    }


    # Normal HTTP Proxying (e.g., REST API, Webhooks)
    location / {
        proxy_pass http://node-backend:3000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}